#!/bin/bash

sudo apt update && sudo apt upgrade
sudo apt install qemu-kvm libvirt-daemon-system virtinst libvirt-clients bridge-utils
sudo systemctl enable libvirtd
sudo systemctl start libvirtd
sudo systemctl status libvirtd #(to ensure it is active and running)
sudo usermod -aG libvirt $USER
sudo usermod -aG kvm $USER
sudo apt install virt-manager

echo "É necessario reiniciar o computador para concluir as alteracoes"
read -p "Gostaria de reinicar agora (y/n)? " answer
case ${answer:0:1} in
    y|Y )
        sudo reboot
    ;;
    * )
	notify-sent "Reinicie seu computator para concluir as alteracoes"
    ;;
esac


sudo reboot
