#!/bin/bash

GREEN='\e[0;92m'
STOP='\e[0m'

printBanner() {
	printf $GREEN
	figlet -c $1
	printf $STOP
}

installProgram(){
apt-cache show $1	
read -p "Você deseja instalar o programa $1 (y/n)?" answer
case ${answer:0:1} in
    y|Y )
        sudo apt install $1	
    ;;
    * )
        echo No
    ;;
esac
}

installYtDlp(){
read -p "Você deseja instalar o programa yt-dlp e suas dependencias (y/n)? " answer
case ${answer:0:1} in
    y|Y )
       sudo apt install yt-dlp
       sudo add-apt-repository ppa:tomtomtom/yt-dlp #Add ppa repo to apt
       sudo apt install ffmpeg #Installing package dependency for yt-dlp
       sudo touch yt-dlp.conf #Criando arquivo de configuracao
       sudo bash -c 'echo "-P $YTDLPFOLDER" >> yt-dlp.conf' #Preenchendo arquivo de  configuracao
       sudo mv yt-dlp.conf /etc/yt-dlp.conf

    ;;
    * )
	    echo No
    ;;
esac
}

echo "Obtendo permissoes para instalar programas"
sudo echo "Permissoes obtidas"

sudo apt install figlet -y

packages=(default-jre synaptic libreoffice cpufetch steam deluge gparted)

for package in ${packages[@]};do
	printBanner $package
	installProgram $package
done



printBanner Yt-Dlp
installYtDlp
