#!/bin/bash

GREEN='\e[0;92m'
STOP='\e[0m'

printBanner() {
	printf $GREEN
	figlet -c $1
	printf $STOP
}


installProgram(){
apt-cache show $1	
read -p "Você deseja instalar o programa $1 (y/n)?" answer
case ${answer:0:1} in
    y|Y )
        sudo apt install $1	
    ;;
    * )
        echo No
    ;;
esac
}

installFlatpak(){
read -p "Você deseja instalar o programa $1 (y/n)?" answer
case ${answer:0:1} in
    y|Y )
        flatpak install flathub $1
    ;;
    * )
        echo No
    ;;
esac
}

installYtDlp(){
read -p "Você deseja instalar o programa yt-dlp e suas dependencias (y/n)? " answer
case ${answer:0:1} in
    y|Y )
       sudo apt install yt-dlp
       sudo add-apt-repository ppa:tomtomtom/yt-dlp #Add ppa repo to apt
       sudo apt install ffmpeg #Installing package dependency for yt-dlp
       sudo touch yt-dlp.conf #Criando arquivo de configuracao
       sudo bash -c 'echo "-P $YTDLPFOLDER" >> yt-dlp.conf' #Preenchendo arquivo de  configuracao
       sudo mv yt-dlp.conf /etc/yt-dlp.conf

    ;;
    * )
	    echo No
    ;;
esac
}

installAniCli(){
	read -p "Você deseja instalar o programa Ani-Cli e suas dependencias (y/n)?  " answer
	case ${answer:0:1} in
	y|Y )
	sudo apt install ani-cli
	sudo apt install mpv
	sudo touch mpv.conf
	sudo bash -c 'echo "#Audio \n ao=alsa \n audio-device=auto" >> mpv.conf
	sudo mv mpv.conf ~/.config/mpv/mpv.conf
}

echo "Obtendo permissoes para instalar programas"
sudo echo "Permissoes obtidas"

sudo apt install figlet -y

packages=($GENERIC_PACKAGES)

flatpacks=($FLATPACKS)

for package in ${packages[@]};do
	printBanner $package
	installProgram $package
done

for flatpak in ${flatpacks[@]};do
		installFlatpak $flatpak
done

printBanner Yt-Dlp
installYtDlp

printBanner Kitty
sudo apt install kitty
kitten themes --reload-in=all Tokyo Night #Mudar Tema do Terminal
sudo mkdir /usr/share/fonts/firacode
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/FiraCode.zip #Baixando fonte para o terminal
sudo 7z x FiraCode.zip -o/usr/share/fonts/firacode/

printBanner Ani-Cli
installAniCli
