#!/bin/bash

echo "Executando update, upgrade e autoRemove"
sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y

echo "Atualizando FlatPacks"
sudo flatpak update

echo "Atualizando Spices"
cinnamon-spice-updater --update-all

echo "Listando pacotes que não foram atualizados por causa de conflitos"
apt list --upgradable
