#!/bin/bash

echo '|=====================|'
echo '|Atualizando o sistema|'
echo '|=====================|'
echo ''
sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y

echo '|=====================|'
echo '|Atualizando FlatPacks|'
echo '|=====================|'
echo ''
sudo flatpak update

echo '|==================|'
echo '|Atualizando Spices|'
echo '|==================|'
echo ''
cinnamon-spice-updater --update-all

echo '|=================================================================|'
echo '|Listando pacotes que não foram atualizados por causa de conflitos|'
echo '|=================================================================|'
echo ''
apt list --upgradable
